### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by venkatesh-thiru** [cyb3rs4k1/sathishkishore.github.io#1]
Excellent portfolio; please fix this typo, sir.

https://github.com/cybersaki/cybersaki.github.io/blob/2935dacd60dc62e5ecef4d41045b75b376d4edf2/scripts/data.js#L19C22-L19C32

Regards
Venkatesh :p

**Comment by cybersaki** [comment]
Done shaar,

Regards,
cybersaki.
